#############################################################################
# Makefile for building: afce
# Generated by qmake (3.1) (Qt 6.10.1)
# Project:  afce.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile afce.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DPROGRAM_DATA_DIR=\"/usr/share/afce/\" -DPROGRAM_VERSION=\"0.9.8\" -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_SVG_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -rdynamic -O2 -frtti -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/qt6 -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtSvg -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -Ibuild -I/usr/lib64/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = afce0.9.8
DISTDIR = /home/gossipauthorxpm/Downloads/afce-0.9.8/build/afce0.9.8
LINK          = g++
LFLAGS        = -rdynamic -Wl,-O1 -Wl,-rpath-link,/usr/lib64
LIBS          = $(SUBLIBS) /usr/lib64/libQt6PrintSupport.so /usr/lib64/libQt6Widgets.so /usr/lib64/libQt6Svg.so /usr/lib64/libQt6Gui.so /usr/lib64/libQt6Xml.so /usr/lib64/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		thelpwindow.cpp \
		zvflowchart.cpp \
		qflowchartstyle.cpp \
		sourcecodegenerator.cpp \
		sourcecodeparser.cpp \
		pseudolangparser.cpp \
		qjson4/QJsonArray.cpp \
		qjson4/QJsonDocument.cpp \
		qjson4/QJsonObject.cpp \
		qjson4/QJsonParseError.cpp \
		qjson4/QJsonParser.cpp \
		qjson4/QJsonValue.cpp \
		qjson4/QJsonValueRef.cpp build/qrc_afce.cpp \
		build/moc_mainwindow.cpp \
		build/moc_thelpwindow.cpp \
		build/moc_zvflowchart.cpp \
		build/moc_sourcecodegenerator.cpp
OBJECTS       = build/main.o \
		build/mainwindow.o \
		build/thelpwindow.o \
		build/zvflowchart.o \
		build/qflowchartstyle.o \
		build/sourcecodegenerator.o \
		build/sourcecodeparser.o \
		build/pseudolangparser.o \
		build/QJsonArray.o \
		build/QJsonDocument.o \
		build/QJsonObject.o \
		build/QJsonParseError.o \
		build/QJsonParser.o \
		build/QJsonValue.o \
		build/QJsonValueRef.o \
		build/qrc_afce.o \
		build/moc_mainwindow.o \
		build/moc_thelpwindow.o \
		build/moc_zvflowchart.o \
		build/moc_sourcecodegenerator.o
DIST          = /usr/lib64/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt6/mkspecs/common/unix.conf \
		/usr/lib64/qt6/mkspecs/common/linux.conf \
		/usr/lib64/qt6/mkspecs/common/sanitize.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt6/mkspecs/common/g++-base.conf \
		/usr/lib64/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt6/mkspecs/qconfig.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qt_config.prf \
		/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt6/mkspecs/features/toolchain.prf \
		/usr/lib64/qt6/mkspecs/features/default_pre.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt6/mkspecs/features/default_post.prf \
		/usr/lib64/qt6/mkspecs/features/rtti.prf \
		/usr/lib64/qt6/mkspecs/features/exceptions.prf \
		/usr/lib64/qt6/mkspecs/features/warn_on.prf \
		/usr/lib64/qt6/mkspecs/features/permissions.prf \
		/usr/lib64/qt6/mkspecs/features/qt.prf \
		/usr/lib64/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt6/mkspecs/features/resources.prf \
		/usr/lib64/qt6/mkspecs/features/moc.prf \
		/usr/lib64/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt6/mkspecs/features/uic.prf \
		/usr/lib64/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt6/mkspecs/features/file_copies.prf \
		/usr/lib64/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt6/mkspecs/features/yacc.prf \
		/usr/lib64/qt6/mkspecs/features/lex.prf \
		afce.pro mainwindow.h \
		thelpwindow.h \
		zvflowchart.h \
		qflowchartstyle.h \
		sourcecodegenerator.h \
		sourcecodeparser.h \
		pseudolangparser.h \
		qjson4/QJsonArray.h \
		qjson4/QJsonDocument.h \
		qjson4/QJsonObject.h \
		qjson4/QJsonParseError.h \
		qjson4/QJsonParser.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonValue.h \
		qjson4/QJsonValueRef.h main.cpp \
		mainwindow.cpp \
		thelpwindow.cpp \
		zvflowchart.cpp \
		qflowchartstyle.cpp \
		sourcecodegenerator.cpp \
		sourcecodeparser.cpp \
		pseudolangparser.cpp \
		qjson4/QJsonArray.cpp \
		qjson4/QJsonDocument.cpp \
		qjson4/QJsonObject.cpp \
		qjson4/QJsonParseError.cpp \
		qjson4/QJsonParser.cpp \
		qjson4/QJsonValue.cpp \
		qjson4/QJsonValueRef.cpp
QMAKE_TARGET  = afce
DESTDIR       = 
TARGET        = afce


first: all
####### Build rules

afce: locale/afce_en_US.qm locale/afce_ru_RU.qm locale/afce_uk_UA.qm $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: afce.pro /usr/lib64/qt6/mkspecs/linux-g++/qmake.conf /usr/lib64/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt6/mkspecs/common/unix.conf \
		/usr/lib64/qt6/mkspecs/common/linux.conf \
		/usr/lib64/qt6/mkspecs/common/sanitize.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt6/mkspecs/common/g++-base.conf \
		/usr/lib64/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt6/mkspecs/qconfig.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qt_config.prf \
		/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt6/mkspecs/features/toolchain.prf \
		/usr/lib64/qt6/mkspecs/features/default_pre.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt6/mkspecs/features/default_post.prf \
		/usr/lib64/qt6/mkspecs/features/rtti.prf \
		/usr/lib64/qt6/mkspecs/features/exceptions.prf \
		/usr/lib64/qt6/mkspecs/features/warn_on.prf \
		/usr/lib64/qt6/mkspecs/features/permissions.prf \
		/usr/lib64/qt6/mkspecs/features/qt.prf \
		/usr/lib64/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt6/mkspecs/features/resources.prf \
		/usr/lib64/qt6/mkspecs/features/moc.prf \
		/usr/lib64/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt6/mkspecs/features/uic.prf \
		/usr/lib64/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt6/mkspecs/features/file_copies.prf \
		/usr/lib64/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt6/mkspecs/features/yacc.prf \
		/usr/lib64/qt6/mkspecs/features/lex.prf \
		afce.pro \
		afce.qrc \
		/usr/lib64/libQt6PrintSupport.prl \
		/usr/lib64/libQt6Widgets.prl \
		/usr/lib64/libQt6Svg.prl \
		/usr/lib64/libQt6Gui.prl \
		/usr/lib64/libQt6Xml.prl \
		/usr/lib64/libQt6Core.prl
	$(QMAKE) -o Makefile afce.pro
/usr/lib64/qt6/mkspecs/features/spec_pre.prf:
/usr/lib64/qt6/mkspecs/common/unix.conf:
/usr/lib64/qt6/mkspecs/common/linux.conf:
/usr/lib64/qt6/mkspecs/common/sanitize.conf:
/usr/lib64/qt6/mkspecs/common/gcc-base.conf:
/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt6/mkspecs/common/g++-base.conf:
/usr/lib64/qt6/mkspecs/common/g++-unix.conf:
/usr/lib64/qt6/mkspecs/qconfig.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testinternals_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_tools_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt6/mkspecs/features/qt_functions.prf:
/usr/lib64/qt6/mkspecs/features/qt_config.prf:
/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt6/mkspecs/features/toolchain.prf:
/usr/lib64/qt6/mkspecs/features/default_pre.prf:
/usr/lib64/qt6/mkspecs/features/resolve_config.prf:
/usr/lib64/qt6/mkspecs/features/default_post.prf:
/usr/lib64/qt6/mkspecs/features/rtti.prf:
/usr/lib64/qt6/mkspecs/features/exceptions.prf:
/usr/lib64/qt6/mkspecs/features/warn_on.prf:
/usr/lib64/qt6/mkspecs/features/permissions.prf:
/usr/lib64/qt6/mkspecs/features/qt.prf:
/usr/lib64/qt6/mkspecs/features/resources_functions.prf:
/usr/lib64/qt6/mkspecs/features/resources.prf:
/usr/lib64/qt6/mkspecs/features/moc.prf:
/usr/lib64/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt6/mkspecs/features/uic.prf:
/usr/lib64/qt6/mkspecs/features/unix/thread.prf:
/usr/lib64/qt6/mkspecs/features/qmake_use.prf:
/usr/lib64/qt6/mkspecs/features/file_copies.prf:
/usr/lib64/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt6/mkspecs/features/yacc.prf:
/usr/lib64/qt6/mkspecs/features/lex.prf:
afce.pro:
afce.qrc:
/usr/lib64/libQt6PrintSupport.prl:
/usr/lib64/libQt6Widgets.prl:
/usr/lib64/libQt6Svg.prl:
/usr/lib64/libQt6Gui.prl:
/usr/lib64/libQt6Xml.prl:
/usr/lib64/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile afce.pro

qmake_all: FORCE


all: Makefile afce

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents locale/afce_en_US.ts locale/afce_ru_RU.ts locale/afce_uk_UA.ts $(DISTDIR)/
	$(COPY_FILE) --parents afce.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h thelpwindow.h zvflowchart.h qflowchartstyle.h sourcecodegenerator.h sourcecodeparser.h pseudolangparser.h qjson4/QJsonArray.h qjson4/QJsonDocument.h qjson4/QJsonObject.h qjson4/QJsonParseError.h qjson4/QJsonParser.h qjson4/QJsonRoot.h qjson4/QJsonValue.h qjson4/QJsonValueRef.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp thelpwindow.cpp zvflowchart.cpp qflowchartstyle.cpp sourcecodegenerator.cpp sourcecodeparser.cpp pseudolangparser.cpp qjson4/QJsonArray.cpp qjson4/QJsonDocument.cpp qjson4/QJsonObject.cpp qjson4/QJsonParseError.cpp qjson4/QJsonParser.cpp qjson4/QJsonValue.cpp qjson4/QJsonValueRef.cpp $(DISTDIR)/
	$(COPY_FILE) --parents locale/afce_en_US.ts locale/afce_ru_RU.ts locale/afce_uk_UA.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_updateqm_make_all: locale/afce_en_US.qm locale/afce_ru_RU.qm locale/afce_uk_UA.qm
compiler_updateqm_clean:
	-$(DEL_FILE) locale/afce_en_US.qm locale/afce_ru_RU.qm locale/afce_uk_UA.qm
locale/afce_en_US.qm: locale/afce_en_US.ts
	/usr/lib64/qt6/bin/lrelease locale/afce_en_US.ts -qm locale/afce_en_US.qm

locale/afce_ru_RU.qm: locale/afce_ru_RU.ts
	/usr/lib64/qt6/bin/lrelease locale/afce_ru_RU.ts -qm locale/afce_ru_RU.qm

locale/afce_uk_UA.qm: locale/afce_uk_UA.ts
	/usr/lib64/qt6/bin/lrelease locale/afce_uk_UA.ts -qm locale/afce_uk_UA.qm

compiler_rcc_make_all: build/qrc_afce.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/qrc_afce.cpp
build/qrc_afce.cpp: afce.qrc \
		/usr/lib64/qt6/libexec/rcc \
		images/paste_clipboard_32_h.png \
		images/arrow.png \
		images/print_32_h.png \
		images/gal.png \
		images/simple.png \
		images/for.png \
		images/binary.png \
		images/ou.png \
		images/toolbar.png \
		images/exit.png \
		images/open_document_32_h.png \
		images/restart-3.png \
		images/restart-2.png \
		images/while.png \
		images/back_16_h.png \
		images/copy_clipboard_32_h.png \
		images/redo_32_h.png \
		images/new_document_32_h.png \
		images/nogal.png \
		images/case.png \
		images/if.png \
		images/undo_32_h.png \
		images/forward_16_h.png \
		images/until.png \
		images/delete_x_32_h.png \
		images/source-code.png \
		images/forc.png \
		images/home_16_h.png \
		images/help-icon.png \
		images/assign.png \
		images/restart-4.png \
		images/io.png \
		images/save_32_h.png \
		images/cut_clipboard_32_h.png \
		images/icon.png \
		images/font.png \
		images/restart-1.png
	/usr/lib64/qt6/libexec/rcc -name afce afce.qrc -o build/qrc_afce.cpp

compiler_moc_predefs_make_all: build/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc_predefs.h
build/moc_predefs.h: /usr/lib64/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -rdynamic -O2 -frtti -Wall -Wextra -dM -E -o build/moc_predefs.h /usr/lib64/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc_mainwindow.cpp build/moc_thelpwindow.cpp build/moc_zvflowchart.cpp build/moc_sourcecodegenerator.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_mainwindow.cpp build/moc_thelpwindow.cpp build/moc_zvflowchart.cpp build/moc_sourcecodegenerator.cpp
build/moc_mainwindow.cpp: mainwindow.h \
		thelpwindow.h \
		zvflowchart.h \
		qflowchartstyle.h \
		build/moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/gossipauthorxpm/Downloads/afce-0.9.8/build/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/gossipauthorxpm/Downloads/afce-0.9.8 -I/home/gossipauthorxpm/Downloads/afce-0.9.8 -I/usr/include/qt6 -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtSvg -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include mainwindow.h -o build/moc_mainwindow.cpp

build/moc_thelpwindow.cpp: thelpwindow.h \
		build/moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/gossipauthorxpm/Downloads/afce-0.9.8/build/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/gossipauthorxpm/Downloads/afce-0.9.8 -I/home/gossipauthorxpm/Downloads/afce-0.9.8 -I/usr/include/qt6 -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtSvg -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include thelpwindow.h -o build/moc_thelpwindow.cpp

build/moc_zvflowchart.cpp: zvflowchart.h \
		qflowchartstyle.h \
		build/moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/gossipauthorxpm/Downloads/afce-0.9.8/build/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/gossipauthorxpm/Downloads/afce-0.9.8 -I/home/gossipauthorxpm/Downloads/afce-0.9.8 -I/usr/include/qt6 -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtSvg -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include zvflowchart.h -o build/moc_zvflowchart.cpp

build/moc_sourcecodegenerator.cpp: sourcecodegenerator.h \
		qjson4/QJsonDocument.h \
		qjson4/QJsonObject.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h \
		qjson4/QJsonArray.h \
		build/moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/gossipauthorxpm/Downloads/afce-0.9.8/build/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/gossipauthorxpm/Downloads/afce-0.9.8 -I/home/gossipauthorxpm/Downloads/afce-0.9.8 -I/usr/include/qt6 -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtSvg -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include sourcecodegenerator.h -o build/moc_sourcecodegenerator.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_updateqm_clean compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/main.o: main.cpp mainwindow.h \
		thelpwindow.h \
		zvflowchart.h \
		qflowchartstyle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o main.cpp

build/mainwindow.o: mainwindow.cpp mainwindow.h \
		thelpwindow.h \
		zvflowchart.h \
		qflowchartstyle.h \
		sourcecodegenerator.h \
		qjson4/QJsonDocument.h \
		qjson4/QJsonObject.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h \
		qjson4/QJsonArray.h \
		sourcecodeparser.h \
		pseudolangparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainwindow.o mainwindow.cpp

build/thelpwindow.o: thelpwindow.cpp thelpwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/thelpwindow.o thelpwindow.cpp

build/zvflowchart.o: zvflowchart.cpp zvflowchart.h \
		qflowchartstyle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/zvflowchart.o zvflowchart.cpp

build/qflowchartstyle.o: qflowchartstyle.cpp qflowchartstyle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qflowchartstyle.o qflowchartstyle.cpp

build/sourcecodegenerator.o: sourcecodegenerator.cpp sourcecodegenerator.h \
		qjson4/QJsonDocument.h \
		qjson4/QJsonObject.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h \
		qjson4/QJsonArray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/sourcecodegenerator.o sourcecodegenerator.cpp

build/sourcecodeparser.o: sourcecodeparser.cpp sourcecodeparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/sourcecodeparser.o sourcecodeparser.cpp

build/pseudolangparser.o: pseudolangparser.cpp pseudolangparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/pseudolangparser.o pseudolangparser.cpp

build/QJsonArray.o: qjson4/QJsonArray.cpp qjson4/QJsonArray.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/QJsonArray.o qjson4/QJsonArray.cpp

build/QJsonDocument.o: qjson4/QJsonDocument.cpp qjson4/QJsonDocument.h \
		qjson4/QJsonObject.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h \
		qjson4/QJsonArray.h \
		qjson4/QJsonParser.h \
		qjson4/QJsonParseError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/QJsonDocument.o qjson4/QJsonDocument.cpp

build/QJsonObject.o: qjson4/QJsonObject.cpp qjson4/QJsonObject.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/QJsonObject.o qjson4/QJsonObject.cpp

build/QJsonParseError.o: qjson4/QJsonParseError.cpp qjson4/QJsonParseError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/QJsonParseError.o qjson4/QJsonParseError.cpp

build/QJsonParser.o: qjson4/QJsonParser.cpp qjson4/QJsonParser.h \
		qjson4/QJsonParseError.h \
		qjson4/QJsonArray.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonObject.h \
		qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/QJsonParser.o qjson4/QJsonParser.cpp

build/QJsonValue.o: qjson4/QJsonValue.cpp qjson4/QJsonValue.h \
		qjson4/QJsonArray.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonObject.h \
		qjson4/QJsonValueRef.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/QJsonValue.o qjson4/QJsonValue.cpp

build/QJsonValueRef.o: qjson4/QJsonValueRef.cpp qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h \
		qjson4/QJsonArray.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonObject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/QJsonValueRef.o qjson4/QJsonValueRef.cpp

build/qrc_afce.o: build/qrc_afce.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_afce.o build/qrc_afce.cpp

build/moc_mainwindow.o: build/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainwindow.o build/moc_mainwindow.cpp

build/moc_thelpwindow.o: build/moc_thelpwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_thelpwindow.o build/moc_thelpwindow.cpp

build/moc_zvflowchart.o: build/moc_zvflowchart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_zvflowchart.o build/moc_zvflowchart.cpp

build/moc_sourcecodegenerator.o: build/moc_sourcecodegenerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_sourcecodegenerator.o build/moc_sourcecodegenerator.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin/ || mkdir -p $(INSTALL_ROOT)/usr/bin/
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_locale: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/afce/locale/ || mkdir -p $(INSTALL_ROOT)/usr/share/afce/locale/
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/locale/afce_en_US.qm $(INSTALL_ROOT)/usr/share/afce/locale/afce_en_US.qm
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/locale/afce_ru_RU.qm $(INSTALL_ROOT)/usr/share/afce/locale/afce_ru_RU.qm
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/locale/afce_uk_UA.qm $(INSTALL_ROOT)/usr/share/afce/locale/afce_uk_UA.qm
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/locale/qt_ru.qm $(INSTALL_ROOT)/usr/share/afce/locale/qt_ru.qm
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/locale/qt_uk.qm $(INSTALL_ROOT)/usr/share/afce/locale/qt_uk.qm
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/locale/qtbase_ru.qm $(INSTALL_ROOT)/usr/share/afce/locale/qtbase_ru.qm
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/locale/qtbase_uk.qm $(INSTALL_ROOT)/usr/share/afce/locale/qtbase_uk.qm
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/locale/qtmultimedia_ru.qm $(INSTALL_ROOT)/usr/share/afce/locale/qtmultimedia_ru.qm
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/locale/qtmultimedia_uk.qm $(INSTALL_ROOT)/usr/share/afce/locale/qtmultimedia_uk.qm

uninstall_locale: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/locale/qtmultimedia_uk.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/locale/qtmultimedia_ru.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/locale/qtbase_uk.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/locale/qtbase_ru.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/locale/qt_uk.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/locale/qt_ru.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/locale/afce_uk_UA.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/locale/afce_ru_RU.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/locale/afce_en_US.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/afce/locale/ 


install_pixmaps: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/pixmaps || mkdir -p $(INSTALL_ROOT)/usr/share/pixmaps
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/afce.png $(INSTALL_ROOT)/usr/share/pixmaps/afce.png

uninstall_pixmaps: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/afce.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 


install_icons: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons || mkdir -p $(INSTALL_ROOT)/usr/share/icons
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/afc.ico $(INSTALL_ROOT)/usr/share/icons/afc.ico

uninstall_icons: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/afc.ico
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/ 


install_desktops: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/applications || mkdir -p $(INSTALL_ROOT)/usr/share/applications
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/afce.desktop $(INSTALL_ROOT)/usr/share/applications/afce.desktop

uninstall_desktops: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/afce.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_helps: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/afce/help/ || mkdir -p $(INSTALL_ROOT)/usr/share/afce/help/
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/help/en_US $(INSTALL_ROOT)/usr/share/afce/help/en_US
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/help/ru_RU $(INSTALL_ROOT)/usr/share/afce/help/ru_RU
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/help/uk_UA $(INSTALL_ROOT)/usr/share/afce/help/uk_UA

uninstall_helps: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/help/uk_UA
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/help/ru_RU
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/help/en_US
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/afce/help/ 


install_generators: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/afce/generators || mkdir -p $(INSTALL_ROOT)/usr/share/afce/generators
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/autoit.json $(INSTALL_ROOT)/usr/share/afce/generators/autoit.json
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/bas256.json $(INSTALL_ROOT)/usr/share/afce/generators/bas256.json
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/c.json $(INSTALL_ROOT)/usr/share/afce/generators/c.json
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/cpp.json $(INSTALL_ROOT)/usr/share/afce/generators/cpp.json
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/e87.json $(INSTALL_ROOT)/usr/share/afce/generators/e87.json
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/freebasic.json $(INSTALL_ROOT)/usr/share/afce/generators/freebasic.json
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/js.json $(INSTALL_ROOT)/usr/share/afce/generators/js.json
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/pas.json $(INSTALL_ROOT)/usr/share/afce/generators/pas.json
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/perl.json $(INSTALL_ROOT)/usr/share/afce/generators/perl.json
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/php.json $(INSTALL_ROOT)/usr/share/afce/generators/php.json
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/py.json $(INSTALL_ROOT)/usr/share/afce/generators/py.json
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/ruby.json $(INSTALL_ROOT)/usr/share/afce/generators/ruby.json
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/generators/vbs.json $(INSTALL_ROOT)/usr/share/afce/generators/vbs.json

uninstall_generators: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/vbs.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/ruby.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/py.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/php.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/perl.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/pas.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/js.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/freebasic.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/e87.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/cpp.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/c.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/bas256.json
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/afce/generators/autoit.json
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/afce/generators/ 


install_mime: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/mime/packages || mkdir -p $(INSTALL_ROOT)/usr/share/mime/packages
	$(QINSTALL) /home/gossipauthorxpm/Downloads/afce-0.9.8/afce.xml $(INSTALL_ROOT)/usr/share/mime/packages/afce.xml

uninstall_mime: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mime/packages/afce.xml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/mime/packages/ 


install: install_target install_locale install_pixmaps install_icons install_desktops install_helps install_generators install_mime  FORCE

uninstall: uninstall_target uninstall_locale uninstall_pixmaps uninstall_icons uninstall_desktops uninstall_helps uninstall_generators uninstall_mime  FORCE

FORCE:

.SUFFIXES:

